version: "3.8"
services:
  cv-builder:
    build: .
    container_name: cv-builder
    ports:
      - "3000:3000"
    volumes:
      - ./storage:/app/storage
      - ./dev.db:/app/dev.db
    env_file:
      - .env
    restart: unless-stopped
